language: r
cache: packages
warnings_are_errors: true
sudo: required
dist: trusty

repos:
  CRAN: https://cloud.r-project.org
  minicran: https://radiant-rstats.github.io/minicran/

r_github_packages:
  - radiant-rstats/radiant.data
  - kevinushey/sourcetools
